Repository JuanDiegoGuerra/Module_2-Capstone, pull requests merged in 2023-05, with the labels that each got.

#24 Displaying Pokemon Data from API
  .vscode/settings.json
  dist/5d66523f643ecf5753f5.png
  dist/8b3d543fa411ab9c2474.png
  dist/index.html
  dist/index.js
  src/images/cancel.png
  src/images/like.png
  src/images/unlike.png
  src/index.html
  src/index.js
  src/modules/api_data.js
  src/modules/likes.js
  src/modules/pokemons.js
  src/style.css
Labels: day1_milestone

#25 Main Styles of the project
  dist/13ba1484c0b21d4d21d1.jpeg
  dist/3e1660a931177c23721e.svg
  dist/index.js
  src/images/International_Pokémon_logo.svg
  src/images/anime_nature_bg_4.jpg
  src/images/pokeball.svg
  src/modules/header.js
  src/modules/pokemons.js
  src/style.css
Labels: day2_milestone

#27 Display comments for a given item on the Comments pop-up
  dist/index.js
  src/modules/comments.js
  src/modules/commentsAPI.js
  src/modules/header.js
  src/modules/pokemons.js
  src/modules/popUp.js
  src/style.css
Labels: day2_milestone

#30 Footer Section
  dist/index.html
  dist/index.js
  src/index.html
  src/style.css
Labels: day1_milestone

#32 Testing pokemons count
  dist/index.js
  package-lock.json
  package.json
  src/__mock__/pokemons.js
  src/__test__/pokemonsCounter.test.js
Labels: day3_milestone

#33 Create new Unit Test for Pokemon Counter
  src/__mock__/pokemons.js
  src/__test__/pokemonsCounter.test.js
Labels: day3_milestone

#34 Update readme.md
  README.md
Labels: documentation

#35 Pokedex - Module 2 - Group Capstone Project
  .babelrc
  .eslintrc.json
  .github/workflows/linters.yml
  .gitignore
  .hintrc
  .stylelintrc.json
  .vscode/settings.json
  README.md
  dist/3e1660a931177c23721e.svg
  dist/4553326abd095b6030cc.jpg
  dist/5d66523f643ecf5753f5.png
  dist/8b3d543fa411ab9c2474.png
  dist/index.html
  dist/index.js
  dist/runtime.js
  package-lock.json
  package.json
  src/__mock__/pokemons.js
  src/__test__/commentsCounter.test.js
  src/__test__/pokemonsCounter.test.js
  src/images/International_Pokémon_logo.svg
  src/images/anime_nature_bg_4.jpg
  src/images/cancel.png
  src/images/like.png
  src/images/pokeball.svg
  src/images/pokedex_capstone_preview.JPG
  src/images/pokemon-logo.jpeg
  src/images/unlike.png
  src/index.html
  src/index.js
  src/modules/api_data.js
  src/modules/commentsAPI.js
  src/modules/commentsCount.js
  src/modules/header.js
  src/modules/likes.js
  src/modules/pokemons.js
  src/modules/popUp.js
  src/style.css
  webpack.config.js
Labels: Finish_Product
